name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install retarded deps from ubuntu
      run: apt install pkg-config libssl-dev
    - name: Install aarch64
      run: rustup target add aarch64-unknown-linux-gnu
    - name: Build
      run: cargo build --target aarch64-unknown-linux-gnu --release --verbose 
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: scraper-aarch64
        path: target/aarch64-unknown-linux-gnu/release/
      

