name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add arm64 arch
      run: sudo dpkg --add-architecture arm64
    - name: Install retarded deps from ubuntu
      run: sudo apt-get install --assume-yes libssl-dev:arm64
    - name: Set aarch env
      run: export PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig
    - name: Install more retarded shit
      run: sudo apt-get install libssl-dev pkg-config -y
    - name: Install aarch64
      run: rustup target add aarch64-unknown-linux-gnu
    - name: Install Cross
      run: cargo install --version 0.1.16 cross
    - name: Build
      run: cargo build --target aarch64-unknown-linux-gnu --release --verbose 
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: scraper-aarch64
        path: target/aarch64-unknown-linux-gnu/release/
      

